// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

public partial class Booking
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Display(Name = "ID")]
    public int BookingID { get; set; }

    public int ClientID { get; set; }

    public int ServiceID { get; set; }

    public int TrainerID { get; set; }

    public DateTime BookingDateTime { get; set; }

    public int SessionsCount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalPrice { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public DateTime CreatedDate { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("Bookings")]
    public virtual Client Client { get; set; }

    [ForeignKey("ServiceID")]
    [InverseProperty("Bookings")]
    public virtual Service Service { get; set; }

    [ForeignKey("TrainerID")]
    [InverseProperty("Bookings")]
    public virtual Trainer Trainer { get; set; }
}