// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

public partial class Booking
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Display(Name = "ID")]
    public int BookingID { get; set; }

    [Display(Name = "ID клиента")]
    public int ClientID { get; set; }

    [Display(Name = "ID услуги")]
    public int ServiceID { get; set; }

    [Display(Name = "ID тренера")]
    public int TrainerID { get; set; }

    [Display(Name = "Дата занятия")]
    public DateTime? BookingDateTime { get; set; }

    [Display(Name = "Кол-во занятий")]
    public int SessionsCount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Общая стоимость")]
    public decimal TotalPrice { get; set; }

    [Required]
    [StringLength(20)]
    [Display(Name = "Статус")]
    public string Status { get; set; }

    [StringLength(500)]
    [Display(Name = "Комментарии")]
    public string Notes { get; set; }

    [Display(Name = "Дата записи")]
    public DateTime? CreatedDate { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("Bookings")]
    public virtual Client Client { get; set; }

    [ForeignKey("ServiceID")]
    [InverseProperty("Bookings")]
    public virtual Service Service { get; set; }

    [ForeignKey("TrainerID")]
    [InverseProperty("Bookings")]
    public virtual Trainer Trainer { get; set; }
}