// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

[Index("Phone", Name = "UQ__Branches__5C7E359E0AA95AE7", IsUnique = true)]
[Index("Email", Name = "UQ__Branches__A9D10534A494CB5B", IsUnique = true)]
public partial class Branch
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int BranchID { get; set; }

    [Required]
    [StringLength(100)]
    public string BranchName { get; set; }

    [Required]
    [StringLength(200)]
    public string Address { get; set; }

    [Required]
    [StringLength(20)]
    public string Phone { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<Trainer> Trainers { get; set; } = new List<Trainer>();
}