// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

public partial class Service
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Display(Name = "ID")]
    public int ServiceID { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Название")]
    public string ServiceName { get; set; }

    [Required]
    [StringLength(50)]
    [Display(Name = "Тип услуги")]
    public string ServiceType { get; set; }

    [Display(Name = "Продолжительность, мин")]
    public int DurationMinutes { get; set; }

    [Display(Name = "Макс. кол-во участников")]
    public int? MaxParticipants { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Цена")]
    public decimal BasePrice { get; set; }

    [StringLength(500)]
    [Display(Name = "Описание")]
    public string Description { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}