// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

[Index("Phone", Name = "UQ__Trainers__5C7E359EBB3BE52D", IsUnique = true)]
[Index("Email", Name = "UQ__Trainers__A9D10534F386976C", IsUnique = true)]
public partial class Trainer
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Display(Name = "ID")]
    public int TrainerID { get; set; }

    [Display(Name = "ID филиала")]
    public int BranchID { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "ФИО")]
    public string FullName { get; set; }

    [Required]
    [StringLength(20)]
    [Display(Name = "Телефон")]
    public string Phone { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Email")]
    public string Email { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Специализация")]
    public string Specialization { get; set; }

    [Required]
    [StringLength(500)]
    [Display(Name = "Образование")]
    public string Education { get; set; }

    [Required]
    [StringLength(1000)]
    [Display(Name = "Опыт работы")]
    public string WorkExperience { get; set; }

    [Required]
    [StringLength(1000)]
    [Display(Name = "Достижения")]
    public string SportsAchievements { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Зарплата")]
    public decimal Salary { get; set; }

    [StringLength(500)]
    [Display(Name = "Фото")]
    public string PhotoPath { get; set; }

    [InverseProperty("Trainer")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("BranchID")]
    [InverseProperty("Trainers")]
    public virtual Branch Branch { get; set; }
}